seed: Home/Desktop/genomaAcol/seed.fasta
ref_gb: Home/Desktop/genomaAcol/reference.gb
range: 120000-170000
repo: plastaumatic
novo_path: /mnt2/software/NOVOPlasty/NOVOPlasty4.3.1.pl
samples:
  genome1: Home/Desktop/genomaAcol/An31.1.fq,Home/Desktop/genomaAcol/An31.2.fq
